import os

MODEL_BIDIRECTIONAL_GRU = "bi_gru"
MODEL_CNN_BIDIRECTIONAL_LSTM = "cnn_bi_lstm"
MODEL_FASTTEXT_DEEP_ANN = "bi_lstm"
MODEL_FASTTEXT_SIMPLE = "simple"
MODEL_ML = "random_forest"

MODEL_SELECTED = MODEL_FASTTEXT_DEEP_ANN

DIR_BASE = os.path.dirname(os.path.realpath(__file__))
DIR_DATASET = DIR_BASE + '/DATASET'
DIR_REPORT = DIR_BASE + '/REPORT'
DIR_EDA = DIR_REPORT + '/EDA'
DIR_IMAGES_EDA = DIR_REPORT + '/IMAGES/EDA'
DIR_IMAGES_HISTORY = DIR_REPORT + '/IMAGES/HISTORY'
DIR_PERFORMENCE_REPORT = DIR_REPORT + '/PERFORMENCE'
DIR_RESOURCES = DIR_BASE + '/resources'


